<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6b1acf1f-8449-47b1-ae07-3a004b7b3ac0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GlobalUsings.cs" />
    <Compile Remove="Users\CreateUser\CreateUserEndpoint.cs" />
    <Compile Remove="Users\CreateUser\CreateUserHandler.cs" />
    <Compile Remove="Users\DeleteUser\DeleteUserEndpoint.cs" />
    <Compile Remove="Users\DeleteUser\DeleteUserHandler.cs" />
    <Compile Remove="Users\GetUserById\GetUserByIdEndpoint.cs" />
    <Compile Remove="Users\GetUserById\GetUserByIdHandler.cs" />
    <Compile Remove="Users\GetUser\GetUsersEndpoint.cs" />
    <Compile Remove="Users\GetUser\GetUsersHandler.cs" />
    <Compile Remove="Users\UpdateUser\UpdateUserEndpoint.cs" />
    <Compile Remove="Users\UpdateUser\UpdateUserHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Dockerfile" />
    <None Remove="Dockerfile.original" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.AspNetCore" Version="7.0.7" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="7.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Users.Infra\Users.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Users\CreateUser\" />
    <Folder Include="Users\DeleteUser\" />
    <Folder Include="Users\GetUserById\" />
    <Folder Include="Users\GetUser\" />
    <Folder Include="Users\UpdateUser\" />
  </ItemGroup>

</Project>
