services:
  usersdb:
    container_name: usersdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=UsersDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_usersdb:/var/lib/postgresql/data
